server:
  port: 8088

spring:
  application:
    name: exam-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/exam
    username: postgres
    password: root
  jpa:
    hibernate:
#      ddl-auto: create
    show-sql: false

logging:
  level:
#    org.springframework.security: TRACE
    com.exammanager: DEBUG