server:
  port: 8088

spring:
  application:
    name: exam-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/exam
    username: postgres
    password: rAyWMlPeVsAs4Du
  jpa:
    hibernate:
#      ddl-auto: create
    show-sql: true

logging:
  level:
#    org.springframework.web: TRACE
    org.exammanager: TRACE